ndtree: ndtree::v1::math Namespace Reference
ndtree::v1::math Namespace Reference
Mathematical utilities.
Functions
template<class Int , CONCEPT_REQUIRES_(Integral< Int >{}) >
constexpr Int ipow (const Int b, const Int e)
Computes b^e for (b,e) integers.
template<class Float , CONCEPT_REQUIRES_(std::is_floating_point< Float >{}) >
constexpr Float floor (Float x)
Constexpr version of cmath floor.
template<class Int , CONCEPT_REQUIRES_(Integral< Int >{}) >
constexpr Int factorial (const Int n) noexcept
Computes the factorial of n.
template<class Int , CONCEPT_REQUIRES_(Integral< Int >{}) >
constexpr Int binomial_coefficient (const Int n, const Int m) noexcept
Computes the binomial coefficient (n m)
Detailed Description
Mathematical utilities.
Function Documentation
template<class Int , CONCEPT_REQUIRES_(Integral< Int >{}) > constexpr Int ndtree::v1::math::ipow (const Int b, const Int e)
Computes b^e for (b,e) integers.
TODO: assert on overflow
Referenced by ndtree::v1::bit::max_value(), ndtree::v1::shift_location_fn::operator()(), ndtree::v1::manifold_neighbors< nd, m >::operator[](), ndtree::v1::bit::to_int(), and ndtree::v1::bit::to_int_r().
template<class Float , CONCEPT_REQUIRES_(std::is_floating_point< Float >{}) > constexpr Float ndtree::v1::math::floor (Float x)
Constexpr version of cmath floor.
TODO: there has to be a better way
Referenced by ndtree::v1::tree< nd >::sibling_group().
template<class Int , CONCEPT_REQUIRES_(Integral< Int >{}) > constexpr Int ndtree::v1::math::factorial (const Int n) noexcept
Computes the factorial of n.
Parameters
n [in] number whose factorial will be computed
TODO: assert on overflow
Referenced by binomial_coefficient().
template<class Int , CONCEPT_REQUIRES_(Integral< Int >{}) > constexpr Int ndtree::v1::math::binomial_coefficient (const Int n, const Int m) noexcept
Computes the binomial coefficient (n m)
TODO: assert n - m >= 0 for unsigned types
References factorial().